export default {
  AUTH_USER: 'AUTH_USER',
  AUTH_USER_SUCCESS: 'AUTH_USER_SUCCESS',
  AUTH_USER_ERROR: 'AUTH_USER_ERROR',
  CLEAR_SENSITIVE_DATA: 'CLEAR_SENSITIVE_DATA',
  CLEAR_SESSION_CACHE: 'CLEAR_SESSION_CACHE',
  SESSION_VERIFIED: 'SESSION_VERIFIED',

  REGIST_USER: 'REGIST_USER',
  REGIST_USER_SUCCESS: 'REGIST_USER_SUCCESS',
  REGIST_USER_ERROR: 'REGIST_USER_ERROR',

  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
  FORGOT_PASSWORD_ERROR: 'FORGOT_PASSWORD_ERROR',

  RESET_PASSWORD: 'RESET_PASSWORD',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_ERROR: 'RESET_PASSWORD_ERROR',
  
  GET_FRAMEWORKS: 'GET_FRAMEWORKS',
  GET_FRAMEWORKS_SUCCESS: 'GET_FRAMEWORKS_SUCCESS',
  GET_FRAMEWORKS_ERROR: 'GET_FRAMEWORKS_ERROR',

  GET_FRAMEWORK_CATEGORIES: 'GET_FRAMEWORK_CATEGORIES',
  GET_FRAMEWORK_CATEGORIES_SUCCESS: 'GET_FRAMEWORK_CATEGORIES_SUCCESS',
  GET_FRAMEWORK_CATEGORIES_ERROR: 'GET_FRAMEWORK_CATEGORIES_ERROR',

  GET_COMPANY_METRICS: 'GET_COMPANY_METRICS',
  GET_COMPANY_METRICS_SUCCESS: 'GET_COMPANY_METRICS_SUCCESS',
  GET_COMPANY_METRICS_ERROR: 'GET_COMPANY_METRICS_ERROR',

  UPDATE_COMPANY_METRIC: 'UPDATE_COMPANY_METRIC',
  UPDATE_COMPANY_METRIC_SUCCESS: 'UPDATE_COMPANY_METRIC_SUCCESS',
  UPDATE_COMPANY_METRIC_ERROR: 'UPDATE_COMPANY_METRIC_ERROR',

  GET_ALL_COMPANY: 'GET_ALL_COMPANY',
  GET_ALL_COMPANY_SUCCESS: 'GET_ALL_COMPANY_SUCCESS',
  GET_ALL_COMPANY_ERROR: 'GET_ALL_COMPANY_ERROR',
  GET_COMPANY: 'GET_COMPANY',
  GET_COMPANY_SUCCESS: 'GET_COMPANY_SUCCESS',
  GET_COMPANY_ERROR: 'GET_COMPANY_ERROR',
  POST_COMPANY: 'POST_COMPANY',
  POST_COMPANY_SUCCESS: 'POST_COMPANY_SUCCESS',
  POST_COMPANY_ERROR: 'POST_COMPANY_ERROR',

  GET_COMPANY_USERS: 'GET_COMPANY_USERS',
  GET_COMPANY_USERS_SUCCESS: 'GET_COMPANY_USERS_SUCCESS',
  GET_COMPANY_USERS_ERROR: 'GET_COMPANY_USERS_ERROR',

  GET_COMPANY_USER_INVITATIONS: 'GET_COMPANY_USER_INVITATIONS',
  GET_COMPANY_USER_INVITATIONS_SUCCESS: 'GET_COMPANY_USER_INVITATIONS_SUCCESS',
  GET_COMPANY_USER_INVITATIONS_ERROR: 'GET_COMPANY_USER_INVITATIONS_ERROR',

  DELETE_COMPANY_USER_INVITATION: 'DELETE_COMPANY_USER_INVITATION',
  DELETE_COMPANY_USER_INVITATION_SUCCESS: 'DELETE_COMPANY_USER_INVITATION_SUCCESS',
  DELETE_COMPANY_USER_INVITATION_ERROR: 'DELETE_COMPANY_USER_INVITATION_ERROR',

  ADD_COMPANY_USER_INVITATION: 'ADD_COMPANY_USER_INVITATION',
  ADD_COMPANY_USER_INVITATION_SUCCESS: 'ADD_COMPANY_USER_INVITATION_SUCCESS',
  ADD_COMPANY_USER_INVITATION_ERROR: 'ADD_COMPANY_USER_INVITATION_ERROR',

  ADD_COMPANY_USER: 'ADD_COMPANY_USER',
  ADD_COMPANY_USER_SUCCESS: 'ADD_COMPANY_USER_SUCCESS',
  ADD_COMPANY_USER_ERROR: 'ADD_COMPANY_USER_ERROR',

  UPDATE_COMPANY_USER: 'UPDATE_COMPANY_USER',
  UPDATE_COMPANY_USER_SUCCESS: 'UPDATE_COMPANY_USER_SUCCESS',
  UPDATE_COMPANY_USER_ERROR: 'UPDATE_COMPANY_USER_ERROR',

  DELETE_COMPANY_USER: 'DELETE_COMPANY_USER',
  DELETE_COMPANY_USER_SUCCESS: 'DELETE_COMPANY_USER_SUCCESS',
  DELETE_COMPANY_USER_ERROR: 'DELETE_COMPANY_USER_ERROR',

  GET_USER_REPORTS: 'GET_USER_REPORTS',
  GET_USER_REPORTS_SUCCESS: 'GET_USER_REPORTS_SUCCESS',
  GET_USER_REPORTS_ERROR: 'GET_USER_REPORTS_ERROR',

  GET_SINGLE_USER_REPORT: 'GET_SINGLE_USER_REPORT',
  GET_SINGLE_USER_REPORT_SUCCESS: 'GET_SINGLE_USER_REPORT_SUCCESS',
  GET_SINGLE_USER_REPORT_ERROR: 'GET_SINGLE_USER_REPORT_ERROR',

  UPDATE_USER_REPORT_CURRENT_REPORT: 'UPDATE_USER_REPORT_CURRENT_REPORT',
  INIT_CURRENT_USER_REPORT: 'INIT_CURRENT_USER_REPORT',

  ADD_USER_REPORT: 'ADD_USER_REPORT',
  ADD_USER_REPORT_SUCCESS: 'ADD_USER_REPORT_SUCCESS',
  ADD_USER_REPORT_ERROR: 'ADD_USER_REPORT_ERROR',

  UPDATE_USER_REPORT: 'UPDATE_USER_REPORT',
  UPDATE_USER_REPORT_SUCCESS: 'UPDATE_USER_REPORT_SUCCESS',
  UPDATE_USER_REPORT_ERROR: 'UPDATE_USER_REPORT_ERROR',
  
  DELETE_USER_REPORT: 'DELETE_USER_REPORT',
  DELETE_USER_REPORT_SUCCESS: 'DELETE_USER_REPORT_SUCCESS',
  DELETE_USER_REPORT_ERROR: 'DELETE_USER_REPORT_ERROR',
  
  UPDATE_REMEMBER_ME: 'UPDATE_REMEMBER_ME',
  UPDATE_USER: 'UPDATE_USER',
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
  UPDATE_USER_ERROR: 'UPDATE_USER_ERROR',

  GET_USER: 'GET_USER',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_ERROR: 'GET_USER_ERROR',
  
  CLEAR_ERROR_RESPONSE: 'CLEAR_ERROR_RESPONSE',

  GET_SUMMARY_DATA: 'GET_SUMMARY_DATA',
  GET_SUMMARY_DATA_SUCCESS: 'GET_SUMMARY_DATA_SUCCESS',
  GET_SUMMARY_DATA_ERROR: 'GET_SUMMARY_DATA_ERROR',

  GET_COMPANY_ALL_ASSETGROUPS: 'GET_COMPANY_ALL_ASSETGROUPS',
  GET_COMPANY_ALL_ASSETGROUPS_SUCCESS: 'GET_COMPANY_ALL_ASSETGROUPS_SUCCESS',
  GET_COMPANY_ALL_ASSETGROUPS_ERROR: 'GET_COMPANY_ALL_ASSETGROUPS_ERROR',
  
  GET_ASSETGROUP_ALL_ASSETS: 'GET_ASSETGROUP_ALL_ASSETS',
  GET_ASSETGROUP_ALL_ASSETS_SUCCESS: 'GET_ASSETGROUP_ALL_ASSETS_SUCCESS',
  GET_ASSETGROUP_ALL_ASSETS_ERROR: 'GET_ASSETGROUP_ALL_ASSETS_ERROR',

  GET_ENGINES: 'GET_ENGINES',
  GET_ENGINES_SUCCESS: 'GET_ENGINES_SUCCESS',
  GET_ENGINES_ERROR: 'GET_ENGINES_ERROR',

  GET_TAGS: 'GET_TAGS',
  GET_TAGS_SUCCESS: 'GET_TAGS_SUCCESS',
  GET_TAGS_ERROR: 'GET_TAGS_ERROR',

  GET_FUELS: 'GET_FUELS',
  GET_FUELS_SUCCESS: 'GET_FUELS_SUCCESS',
  GET_FUELS_ERROR: 'GET_FUELS_ERROR',

  GET_EMISSIONS: 'GET_EMISSIONS',
  GET_EMISSIONS_SUCCESS: 'GET_EMISSIONS_SUCCESS',
  GET_EMISSIONS_ERROR: 'GET_EMISSIONS_ERROR',

  GET_SPENDCOSTS: 'GET_SPENDCOSTS',
  GET_SPENDCOSTS_SUCCESS: 'GET_SPENDCOSTS_SUCCESS',
  GET_SPENDCOSTS_ERROR: 'GET_SPENDCOSTS_ERROR',

  GET_ASSETENGINE_AVAIL_FUELS: 'GET_ASSETENGINE_AVAIL_FUELS',
  GET_ASSETENGINE_AVAIL_FUELS_SUCCESS: 'GET_ASSETENGINE_AVAIL_FUELS_SUCCESS',
  GET_ASSETENGINE_AVAIL_FUELS_ERROR: 'GET_ASSETENGINE_AVAIL_FUELS_ERROR',

  ADD_ASSET: 'ADD_ASSET',
  ADD_ASSET_SUCCESS: 'ADD_ASSET_SUCCESS',
  ADD_ASSET_ERROR: 'ADD_ASSET_ERROR',

  DELETE_ASSET: 'DELETE_ASSET',
  DELETE_ASSET_SUCCESS: 'DELETE_ASSET_SUCCESS',
  DELETE_ASSET_ERROR: 'DELETE_ASSET_ERROR',

  UPDATE_ASSET: 'UPDATE_ASSET',
  UPDATE_ASSET_SUCCESS: 'UPDATE_ASSET_SUCCESS',
  UPDATE_ASSET_ERROR: 'UPDATE_ASSET_ERROR',

  ADD_LEASE_ASSET: 'ADD_LEASE_ASSET',
  ADD_LEASE_ASSET_SUCCESS: 'ADD_LEASE_ASSET_SUCCESS',
  ADD_LEASE_ASSET_ERROR: 'ADD_LEASE_ASSET_ERROR',

  UPDATE_LEASE_ASSET: 'UPDATE_LEASE_ASSET',
  UPDATE_LEASE_ASSET_SUCCESS: 'UPDATE_LEASE_ASSET_SUCCESS',
  UPDATE_LEASE_ASSET_ERROR: 'UPDATE_LEASE_ASSET_ERROR',
  
  ADD_ASSETGROUP: 'ADD_ASSETGROUP',
  ADD_ASSETGROUP_SUCCESS: 'ADD_ASSETGROUP_SUCCESS',
  ADD_ASSETGROUP_ERROR: 'ADD_ASSETGROUP_ERROR',

  DELETE_ASSETGROUP: 'DELETE_ASSETGROUP',
  DELETE_ASSETGROUP_SUCCESS: 'DELETE_ASSETGROUP_SUCCESS',
  DELETE_ASSETGROUP_ERROR: 'DELETE_ASSETGROUP_ERROR',

  UPDATE_ASSETGROUP: 'UPDATE_ASSETGROUP', 
  UPDATE_ASSETGROUP_SUCCESS: 'UPDATE_ASSETGROUP_SUCCESS',
  UPDATE_ASSETGROUP_ERROR: 'UPDATE_ASSETGROUP_ERROR',

  ADD_ASSIGNABLEASSET: 'ADD_ASSIGNABLEASSET',
  ADD_ASSIGNABLEASSET_SUCCESS: 'ADD_ASSIGNABLEASSET_SUCCESS',
  ADD_ASSIGNABLEASSET_ERROR: '  ADD_ASSIGNABLEASSET_ERROR',

  DELETE_ASSIGNABLEASSET: 'DELETE_ASSIGNABLEASSET',
  DELETE_ASSIGNABLEASSET_SUCCESS: 'DELETE_ASSIGNABLEASSET_SUCCESS',
  DELETE_ASSIGNABLEASSET_ERROR: 'DELETE_ASSIGNABLEASSET_ERROR',

  ADD_ASSETENGINE: 'ADD_ASSETENGINE',
  ADD_ASSETENGINE_SUCCESS: 'ADD_ASSETENGINE_SUCCESS',
  ADD_ASSETENGINE_ERROR: 'ADD_ASSETENGINE_ERROR',

  DELETE_ASSETENGINE: 'DELETE_ASSETENGINE',
  DELETE_ASSETENGINE_SUCCESS: 'DELETE_ASSETENGINE_SUCCESS',
  DELETE_ASSETENGINE_ERROR: 'DELETE_ASSETENGINE_ERROR',

  ADD_REFRIGERATOR: 'ADD_REFRIGERATOR',
  ADD_REFRIGERATOR_SUCCESS: 'ADD_REFRIGERATOR_SUCCESS',
  ADD_REFRIGERATOR_ERROR: 'ADD_REFRIGERATOR_ERROR',

  DELETE_REFRIGERATOR: 'DELETE_REFRIGERATOR',
  DELETE_REFRIGERATOR_SUCCESS: 'DELETE_REFRIGERATOR_SUCCESS',
  DELETE_REFRIGERATOR_ERROR: 'DELETE_REFRIGERATOR_ERROR',

  GET_ASSET_ALL_PRODUCTS: 'GET_ASSET_ALL_PRODUCTS',
  GET_ASSET_ALL_PRODUCTS_SUCCESS: 'GET_ASSET_ALL_PRODUCTS_SUCCESS',
  GET_ASSET_ALL_PRODUCTS_ERROR: 'GET_ASSET_ALL_PRODUCTS_ERROR',
  
  GET_ASSET_ALL_FUELCONSUMPTIONS: 'GET_ASSET_ALL_FUELCONSUMPTIONS',
  GET_ASSET_ALL_FUELCONSUMPTIONS_ERROR: 'GET_ASSET_ALL_FUELCONSUMPTIONS_ERROR',
  GET_ASSET_ALL_FUELCONSUMPTIONS_SUCCESS: 'GET_ASSET_ALL_FUELCONSUMPTIONS_SUCCESS',

  GET_ASSET_ALL_UTILITIES: 'GET_ASSET_ALL_UTILITIES',
  GET_ASSET_ALL_UTILITIES_SUCCESS: 'GET_ASSET_ALL_UTILITIES_SUCCESS',
  GET_ASSET_ALL_UTILITIES_ERROR: 'GET_ASSET_ALL_UTILITIES_ERROR',

  GET_ASSET_ALL_WASTES: 'GET_ASSET_ALL_WASTES',
  GET_ASSET_ALL_WASTES_SUCCESS: 'GET_ASSET_ALL_WASTES_SUCCESS',
  GET_ASSET_ALL_WASTES_ERROR: 'GET_ASSET_ALL_WASTES_ERROR',

  GET_ASSET_ALL_REFRIGERATORCONSUMPTIONS: 'GET_ASSET_ALL_REFRIGERATORCONSUMPTIONS',
  GET_ASSET_ALL_REFRIGERATORCONSUMPTIONS_ERROR: 'GET_ASSET_ALL_REFRIGERATORCONSUMPTIONS_ERROR',
  GET_ASSET_ALL_REFRIGERATORCONSUMPTIONS_SUCCESS: 'GET_ASSET_ALL_REFRIGERATORCONSUMPTIONS_SUCCESS',

  GET_ASSET_ENGINES: 'GET_ASSET_ENGINES',
  GET_ASSET_ENGINES_SUCCESS: 'GET_ASSET_ENGINES_SUCCESS',
  GET_ASSET_ENGINES_ERROR: 'GET_ASSET_ENGINES_ERROR',

  GET_ASSET_REFRIGERATORS: 'GET_ASSET_REFRIGERATORS',
  GET_ASSET_REFRIGERATORS_SUCCESS: 'GET_ASSET_REFRIGERATORS_SUCCESS',
  GET_ASSET_REFRIGERATORS_ERROR: 'GET_ASSET_REFRIGERATORS_ERROR',

  GET_ASSIGNED_RECORDS: 'GET_ASSIGNED_RECORDS',
  GET_ASSIGNED_RECORDS_SUCCESS: 'GET_ASSIGNED_RECORDS_SUCCESS',
  GET_ASSIGNED_RECORDS_ERROR: 'GET_ASSIGNED_RECORDS_ERROR',

  GET_CHILDREN_COMPANY: 'GET_CHILDREN_COMPANY',
  GET_CHILDREN_COMPANY_SUCCESS: 'GET_CHILDREN_COMPANY_SUCCESS',
  GET_CHILDREN_COMPANY_ERROR: 'GET_CHILDREN_COMPANY_ERROR',

  GET_PARENTS_COMPANY: 'GET_PARENTS_COMPANY',
  GET_PARENTS_COMPANY_SUCCESS: 'GET_PARENTS_COMPANY_SUCCESS',
  GET_PARENTS_COMPANY_ERROR: 'GET_PARENTS_COMPANY_ERROR', 

  ADD_ASSIGN_RECORD: 'ADD_ASSIGN_RECORD',
  ADD_ASSIGN_RECORD_SUCCESS: 'ADD_ASSIGN_RECORD_SUCCESS',
  ADD_ASSIGN_RECORD_ERROR: 'ADD_ASSIGN_RECORD_ERROR',

  UPDATE_ASSIGN_RECORD: 'UPDATE_ASSIGN_RECORD',
  UPDATE_ASSIGN_RECORD_SUCCESS: 'UPDATE_ASSIGN_RECORD_SUCCESS',
  UPDATE_ASSIGN_RECORD_ERROR: 'UPDATE_ASSIGN_RECORD_ERROR',

  DELETE_ASSIGN_RECORD: 'DELETE_ASSIGN_RECORD',
  DELETE_ASSIGN_RECORD_SUCCESS: 'DELETE_ASSIGN_RECORD_SUCCESS',
  DELETE_ASSIGN_RECORD_ERROR: 'DELETE_ASSIGN_RECORD_ERROR',

  GET_COMPANY_TRAVEL: 'GET_COMPANY_TRAVEL',
  GET_COMPANY_TRAVEL_SUCCESS: 'GET_COMPANY_TRAVEL_SUCCESS',
  GET_COMPANY_TRAVEL_ERROR: 'GET_COMPANY_TRAVEL_ERROR',

  ADD_COMPANY_TRAVEL: 'ADD_COMPANY_TRAVEL',
  ADD_COMPANY_TRAVEL_SUCCESS: 'ADD_COMPANY_TRAVEL_SUCCESS',
  ADD_COMPANY_TRAVEL_ERROR: 'ADD_COMPANY_TRAVEL_ERROR',

  DELETE_COMPANY_TRAVEL: 'DELETE_COMPANY_TRAVEL',
  DELETE_COMPANY_TRAVEL_SUCCESS: 'DELETE_COMPANY_TRAVEL_SUCCESS',
  DELETE_COMPANY_TRAVEL_ERROR: 'DELETE_COMPANY_TRAVEL_ERROR',

  GET_COMPANY_PURCHASES: 'GET_COMPANY_PURCHASES',
  GET_COMPANY_PURCHASES_SUCCESS: 'GET_COMPANY_PURCHASES_SUCCESS',
  GET_COMPANY_PURCHASES_ERROR: 'GET_COMPANY_PURCHASES_ERROR',

  ADD_COMPANY_PURCHASES: 'ADD_COMPANY_PURCHASES',
  ADD_COMPANY_PURCHASES_SUCCESS: 'ADD_COMPANY_PURCHASES_SUCCESS',
  ADD_COMPANY_PURCHASES_ERROR: 'ADD_COMPANY_PURCHASES_ERROR',

  DELETE_COMPANY_PURCHASES: 'DELETE_COMPANY_PURCHASES',
  DELETE_COMPANY_PURCHASES_SUCCESS: 'DELETE_COMPANY_PURCHASES_SUCCESS',
  DELETE_COMPANY_PURCHASES_ERROR: 'DELETE_COMPANY_PURCHASES_ERROR',

  UPDATE_COMPANY_PURCHASES: 'UPDATE_COMPANY_PURCHASES',
  UPDATE_COMPANY_PURCHASES_SUCCESS: 'UPDATE_COMPANY_PURCHASES_SUCCESS',
  UPDATE_COMPANY_PURCHASES_ERROR: 'UPDATE_COMPANY_PURCHASES_ERROR',

  GET_COMPANY_COMMUTE: 'GET_COMPANY_COMMUTE',
  GET_COMPANY_COMMUTE_SUCCESS: 'GET_COMPANY_COMMUTE_SUCCESS',
  GET_COMPANY_COMMUTE_ERROR: 'GET_COMPANY_COMMUTE_ERROR',

  ADD_COMPANY_COMMUTE: 'ADD_COMPANY_COMMUTE',
  ADD_COMPANY_COMMUTE_SUCCESS: 'ADD_COMPANY_COMMUTE_SUCCESS',
  ADD_COMPANY_COMMUTE_ERROR: 'ADD_COMPANY_COMMUTE_ERROR',

  UPDATE_COMPANY_COMMUTE: 'UPDATE_COMPANY_COMMUTE',
  UPDATE_COMPANY_COMMUTE_SUCCESS: 'UPDATE_COMPANY_COMMUTE_SUCCESS',
  UPDATE_COMPANY_COMMUTE_ERROR: 'UPDATE_COMPANY_COMMUTE_ERROR',

  DELETE_COMPANY_COMMUTE: 'DELETE_COMPANY_COMMUTE',
  DELETE_COMPANY_COMMUTE_SUCCESS: 'DELETE_COMPANY_COMMUTE_SUCCESS',
  DELETE_COMPANY_COMMUTE_ERROR: 'DELETE_COMPANY_COMMUTE_ERROR',

  GET_COMPANY_PRODUCT: 'GET_COMPANY_PRODUCT',
  GET_COMPANY_PRODUCT_SUCCESS: 'GET_COMPANY_PRODUCT_SUCCESS',
  GET_COMPANY_PRODUCT_ERROR: 'GET_COMPANY_PRODUCT_ERROR',

  ADD_COMPANY_PRODUCT: 'ADD_COMPANY_PRODUCT',
  ADD_COMPANY_PRODUCT_SUCCESS: 'ADD_COMPANY_PRODUCT_SUCCESS',
  ADD_COMPANY_PRODUCT_ERROR: 'ADD_COMPANY_PRODUCT_ERROR',

  UPDATE_COMPANY_PRODUCT: 'UPDATE_COMPANY_PRODUCT',
  UPDATE_COMPANY_PRODUCT_SUCCESS: 'UPDATE_COMPANY_PRODUCT_SUCCESS',
  UPDATE_COMPANY_PRODUCT_ERROR: 'UPDATE_COMPANY_PRODUCT_ERROR',

  DELETE_COMPANY_PRODUCT: 'DELETE_COMPANY_PRODUCT',
  DELETE_COMPANY_PRODUCT_SUCCESS: 'DELETE_COMPANY_PRODUCT_SUCCESS',
  DELETE_COMPANY_PRODUCT_ERROR: 'DELETE_COMPANY_PRODUCT_ERROR',

  GET_COMPANY_PRODUCT_MATERIAL: 'GET_COMPANY_PRODUCT_MATERIAL',
  GET_COMPANY_PRODUCT_MATERIAL_SUCCESS: 'GET_COMPANY_PRODUCT_MATERIAL_SUCCESS',
  GET_COMPANY_PRODUCT_MATERIAL_ERROR: 'GET_COMPANY_PRODUCT_MATERIAL_ERROR',

  ADD_COMPANY_PRODUCT_MATERIAL: 'ADD_COMPANY_PRODUCT_MATERIAL',
  ADD_COMPANY_PRODUCT_MATERIAL_SUCCESS: 'ADD_COMPANY_PRODUCT_MATERIAL_SUCCESS',
  ADD_COMPANY_PRODUCT_MATERIAL_ERROR: 'ADD_COMPANY_PRODUCT_MATERIAL_ERROR',

  UPDATE_COMPANY_PRODUCT_MATERIAL: 'UPDATE_COMPANY_PRODUCT_MATERIAL',
  UPDATE_COMPANY_PRODUCT_MATERIAL_SUCCESS: 'UPDATE_COMPANY_PRODUCT_MATERIAL_SUCCESS',
  UPDATE_COMPANY_PRODUCT_MATERIAL_ERROR: 'UPDATE_COMPANY_PRODUCT_MATERIAL_ERROR',

  DELETE_COMPANY_PRODUCT_MATERIAL: 'DELETE_COMPANY_PRODUCT_MATERIAL',
  DELETE_COMPANY_PRODUCT_MATERIAL_SUCCESS: 'DELETE_COMPANY_PRODUCT_MATERIAL_SUCCESS',
  DELETE_COMPANY_PRODUCT_MATERIAL_ERROR: 'DELETE_COMPANY_PRODUCT_MATERIAL_ERROR',

  GET_MATERIAL: 'GET_MATERIAL',
  GET_MATERIAL_SUCCESS: 'GET_MATERIAL_SUCCESS',
  GET_MATERIAL_ERROR: 'GET_MATERIAL_ERROR',

  GET_COMPANY_SOLD_PRODUCT: 'GET_COMPANY_SOLD_PRODUCT',
  GET_COMPANY_SOLD_PRODUCT_SUCCESS: 'GET_COMPANY_SOLD_PRODUCT_SUCCESS',
  GET_COMPANY_SOLD_PRODUCT_ERROR: 'GET_COMPANY_SOLD_PRODUCT_ERROR',

  ADD_COMPANY_SOLD_PRODUCT: 'ADD_COMPANY_SOLD_PRODUCT',
  ADD_COMPANY_SOLD_PRODUCT_SUCCESS: 'ADD_COMPANY_SOLD_PRODUCT_SUCCESS',
  ADD_COMPANY_SOLD_PRODUCT_ERROR: 'ADD_COMPANY_SOLD_PRODUCT_ERROR',

  UPDATE_COMPANY_SOLD_PRODUCT: 'UPDATE_COMPANY_SOLD_PRODUCT',
  UPDATE_COMPANY_SOLD_PRODUCT_SUCCESS: 'UPDATE_COMPANY_SOLD_PRODUCT_SUCCESS',
  UPDATE_COMPANY_SOLD_PRODUCT_ERROR: 'UPDATE_COMPANY_SOLD_PRODUCT_ERROR',

  DELETE_COMPANY_SOLD_PRODUCT: 'DELETE_COMPANY_SOLD_PRODUCT',
  DELETE_COMPANY_SOLD_PRODUCT_SUCCESS: 'DELETE_COMPANY_SOLD_PRODUCT_SUCCESS',
  DELETE_COMPANY_SOLD_PRODUCT_ERROR: 'DELETE_COMPANY_SOLD_PRODUCT_ERROR',

  GET_COMPANY_UTILITY: 'GET_COMPANY_UTILITY',
  GET_COMPANY_UTILITY_SUCCESS: 'GET_COMPANY_UTILITY_SUCCESS',
  GET_COMPANY_UTILITY_ERROR: 'GET_COMPANY_UTILITY_ERROR',

  ADD_COMPANY_UTILITY: 'ADD_COMPANY_UTILITY',
  ADD_COMPANY_UTILITY_SUCCESS: 'ADD_COMPANY_UTILITY_SUCCESS',
  ADD_COMPANY_UTILITY_ERROR: 'ADD_COMPANY_UTILITY_ERROR',

  UPDATE_COMPANY_UTILITY: 'UPDATE_COMPANY_UTILITY',
  UPDATE_COMPANY_UTILITY_SUCCESS: 'UPDATE_COMPANY_UTILITY_SUCCESS',
  UPDATE_COMPANY_UTILITY_ERROR: 'UPDATE_COMPANY_UTILITY_ERROR',

  DELETE_COMPANY_UTILITY: 'DELETE_COMPANY_UTILITY',
  DELETE_COMPANY_UTILITY_SUCCESS: 'DELETE_COMPANY_UTILITY_SUCCESS',
  DELETE_COMPANY_UTILITY_ERROR: 'DELETE_COMPANY_UTILITY_ERROR',

  GET_COMPANY_EMPLOYEE: 'GET_COMPANY_EMPLOYEE',
  GET_COMPANY_EMPLOYEE_SUCCESS: 'GET_COMPANY_EMPLOYEE_SUCCESS',
  GET_COMPANY_EMPLOYEE_ERROR: 'GET_COMPANY_EMPLOYEE_ERROR',

  ADD_COMPANY_EMPLOYEE: 'ADD_COMPANY_EMPLOYEE',
  ADD_COMPANY_EMPLOYEE_SUCCESS: 'ADD_COMPANY_EMPLOYEE_SUCCESS',
  ADD_COMPANY_EMPLOYEE_ERROR: 'ADD_COMPANY_EMPLOYEE_ERROR',

  UPDATE_COMPANY_EMPLOYEE: 'UPDATE_COMPANY_EMPLOYEE',
  UPDATE_COMPANY_EMPLOYEE_SUCCESS: 'UPDATE_COMPANY_EMPLOYEE_SUCCESS',
  UPDATE_COMPANY_EMPLOYEE_ERROR: 'UPDATE_COMPANY_EMPLOYEE_ERROR',

  DELETE_COMPANY_EMPLOYEE: 'DELETE_COMPANY_EMPLOYEE',
  DELETE_COMPANY_EMPLOYEE_SUCCESS: 'DELETE_COMPANY_EMPLOYEE_SUCCESS',
  DELETE_COMPANY_EMPLOYEE_ERROR: 'DELETE_COMPANY_EMPLOYEE_ERROR',

  GET_COMPANY_WASTE: 'GET_COMPANY_WASTE',
  GET_COMPANY_WASTE_SUCCESS: 'GET_COMPANY_WASTE_SUCCESS',
  GET_COMPANY_WASTE_ERROR: 'GET_COMPANY_WASTE_ERROR',

  ADD_COMPANY_WASTE: 'ADD_COMPANY_WASTE',
  ADD_COMPANY_WASTE_SUCCESS: 'ADD_COMPANY_WASTE_SUCCESS',
  ADD_COMPANY_WASTE_ERROR: 'ADD_COMPANY_WASTE_ERROR',

  UPDATE_COMPANY_WASTE: 'UPDATE_COMPANY_WASTE',
  UPDATE_COMPANY_WASTE_SUCCESS: 'UPDATE_COMPANY_WASTE_SUCCESS',
  UPDATE_COMPANY_WASTE_ERROR: 'UPDATE_COMPANY_WASTE_ERROR',

  DELETE_COMPANY_WASTE: 'DELETE_COMPANY_WASTE',
  DELETE_COMPANY_WASTE_SUCCESS: 'DELETE_COMPANY_WASTE_SUCCESS',
  DELETE_COMPANY_WASTE_ERROR: 'DELETE_COMPANY_WASTE_ERROR',

  GET_ALL_ASSIGNED_TO: 'GET_ALL_ASSIGNED_TO',
  GET_ASSIGNED_TO_RECORDS: 'GET_ASSIGNED_TO_RECORDS',
  GET_ASSIGNED_TO_RECORDS_SUCCESS: 'GET_ASSIGNED_TO_RECORDS_SUCCESS',
  GET_ASSIGNED_TO_RECORDS_ERROR: 'GET_ASSIGNED_TO_RECORDS_ERROR',

  GET_ALL_ASSIGNED_FROM: 'GET_ALL_ASSIGNED_FROM',
  GET_ASSIGNED_FROM_RECORDS: 'GET_ASSIGNED_FROM_RECORDS',
  GET_ASSIGNED_FROM_RECORDS_SUCCESS: 'GET_ASSIGNED_FROM_RECORDS_SUCCESS',
  GET_ASSIGNED_FROM_RECORDS_ERROR: 'GET_ASSIGNED_FROM_RECORDS_ERROR',

  GET_ANALYTIC_DATA: 'GET_ANALYTIC_DATA',
  GET_ANALYTIC_DATA_SUCCESS: 'GET_ANALYTIC_DATA_SUCCESS',
  GET_ANALYTIC_DATA_ERROR: 'GET_ANALYTIC_DATA_ERROR',

  CLEAR_CURRENT_CONFIG: 'CLEAR_CURRENT_CONFIG',
  SET_CURRENT_CONFIG: 'SET_CURRENT_CONFIG',
  UPDATE_CURRENT_CONFIG: 'UPDATE_CURRENT_CONFIG',
  UPDATE_CURRENT_DOMAIN_ITEMS: 'UPDATE_CURRENT_DOMAIN_ITEMS',
  UPDATE_CURRENT_DOMAIN_ITEMS_BY_ARRAY: 'UPDATE_CURRENT_DOMAIN_ITEMS_BY_ARRAY',
  UPDATE_CURRENT_XAXIS_ITEMS: 'UPDATE_CURRENT_XAXIS_ITEMS',
  UPDATE_CURRENT_XAXIS_ITEMS_BY_ARRAY: 'UPDATE_CURRENT_XAXIS_ITEMS_BY_ARRAY',
  UPDATE_CURRENT_TIME: 'UPDATE_CURRENT_TIME',

  ADD_TMP_ANALYTIC_REPORT: 'ADD_TMP_ANALYTIC_REPORT',

  GET_ANALYTIC_REPORTS: 'GET_ANALYTIC_REPORTS',
  GET_ANALYTIC_REPORTS_SUCCESS: 'GET_ANALYTIC_REPORTS_SUCCESS',
  GET_ANALYTIC_REPORTS_ERROR: 'GET_ANALYTIC_REPORTS_ERROR',
  
  ADD_ANALYTIC_REPORT_SUCCESS: 'ADD_ANALYTIC_REPORT_SUCCESS',
  ADD_ANALYTIC_REPORT: 'ADD_ANALYTIC_REPORT',
  ADD_ANALYTIC_REPORT_ERROR: 'ADD_ANALYTIC_REPORT_ERROR',

  UPDATE_ANALYTIC_REPORT: 'UPDATE_ANALYTIC_REPORT',
  UPDATE_ANALYTIC_REPORT_SUCCESS: 'UPDATE_ANALYTIC_REPORT_SUCCESS',
  UPDATE_ANALYTIC_REPORT_ERROR: 'UPDATE_ANALYTIC_REPORT_ERROR',

  UPDATE_ANALYTIC_REPORT_CONFIGS: 'UPDATE_ANALYTIC_REPORT_CONFIGS',
  UPDATE_ANALYTIC_REPORT_CONFIGS_SUCCESS: 'UPDATE_ANALYTIC_REPORT_CONFIGS_SUCCESS',
  UPDATE_ANALYTIC_REPORT_CONFIGS_ERROR: 'UPDATE_ANALYTIC_REPORT_CONFIGS_ERROR',

  DELETE_ANALYTIC_REPORT: 'DELETE_ANALYTIC_REPORT',
  DELETE_ANALYTIC_REPORT_SUCCESS: 'DELETE_ANALYTIC_REPORT_SUCCESS',
  DELETE_ANALYTIC_REPORT_ERROR: 'DELETE_ANALYTIC_REPORT_ERROR',
};